### ISSUE TITLE
The weights are unavailable

### ISSUE THREAD

**Issue by divyaYK** [minar09/MGN-Py3#2]
Hi,

I just cloned your repository but I couldn't download the weights and the given link says the item is no longer available.
Could you help me with this?

**Comment by minar09** [comment]
Hi @divyaYK, I updated the readme file with the updated links from the original repository. Now you should be able to download the weights and data. Thank you. 
For more information, you can refer to the repository from the original paper authors: https://github.com/bharat-b7/MultiGarmentNetwork

**Comment by divyaYK** [comment]
Thank you so much, @minar09
